name: sattva_rtr_construction_split_wise
description: Construction Transaction Management Application
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  get_storage: ^2.1.1
  http: ^1.0.0
  dio: ^4.0.6
  cupertino_icons: ^1.0.2
  cross_file: any
  mime_type: ^1.0.0
  image_picker_for_web: ^2.1.8
  image_picker: ^0.8.7+1
  mime: any
  universal_html: ^2.2.1
  dartz: ^0.10.1
  firebase_core: ^2.24.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

